# Generated by Django 4.2 on 2024-08-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryZenApp', '0002_rename_name_inventory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='value',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
